# Generated by Django 3.1.2 on 2020-10-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dadosml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelml', models.CharField(max_length=20)),
                ('accuracy', models.FloatField()),
                ('prediction', models.FloatField()),
                ('label', models.CharField(max_length=2)),
                ('features', models.CharField(max_length=900)),
            ],
        ),
    ]
